### ISSUE TITLE
Annotations render incorrectly on some posts 

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse-annotator#224] opened 2022-02-04 15:53 UTC
POPREBEL ethnographers report that some post, when viewed in the back end with their annotations, render incorrectly, in a way that makes that view useless. For example, here you can see highlights starting and stopping in mid-word:  

![image](https://user-images.githubusercontent.com/1976806/152557943-c8875a82-517d-4e8c-8723-808e140aa3b8.png)

([here](https://edgeryders.eu/annotator/topics/15518#post-number-16) it is on the platform)

Annotation store correctly, for example [this](https://edgeryders.eu/annotator/text_annotations/30217). The sentence that should be higlighted is "Twój stosunek do tego co się dzieje jeśli chodzi o prawo do wykonywania aborcji w Polsce?", and it should be assigned the code `Z Values and Beliefs - Category → abortion`.  But the rendering is incorrect: 

![image](https://user-images.githubusercontent.com/1976806/152559236-d412cca1-8472-4812-bbe6-80ea1f8dc06a.png)

I initially hypothesized a role of emoticons or graphics, so I created and coded [this test topic](https://edgeryders.eu/t/test-topic-for-open-ethnographer/16612), but could not reproduce the issue.

**Comment by damingo** [comment] 2022-02-09 22:09
Turns out this is the same issue as https://github.com/edgeryders/discourse-annotator/issues/210 which was caused by a post being edited after it was annotated.

The [annotation](https://edgeryders.eu/annotator/text_annotations/30217) you mentioned was created on April 20, '21 but on May 20, '21 a paragraph was added to the start of the annotated [post](https://edgeryders.eu/t/poprebel-polska-interviews/15518/16). As annotations are anchored to paragraphs, this messed up all annotations in the post. Internally the annotations are still present, but annotator is now unable to display them properly. When the beginning of a long post is edited is basically the worst case (and happens rarely) as it messes up all annotations after the edited paragraph.

I'll start working on a solution. Closing this issue as we already have https://github.com/edgeryders/discourse-annotator/issues/6 to track it.

**Closed by damingo** 2022-02-09 22:09 UTC
Labels: bug
